### ISSUE TITLE
beinleumi fails on  waiting for selector `#matafLogoutLink` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by razaz** [eshaham/israeli-bank-scrapers#691]
manually modifying the waitForPostLogin method to do the below resolves the issue.

async function waitForPostLogin(page) {
  await sleep(1000);
  return Promise.race([(0, _elementsInteractions.waitUntilElementFound)(page, '#matafLogoutLink', true), (0, _elementsInteractions.waitUntilElementFound)(page, '#validationMsg', true)]);
}

async function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

**Comment by esakal** [comment]
Hi, I'm not sure why sleep helps here as you are waiting for 1 second before continuing. Please try the following:

```
export async function waitForPostLogin(page: Page) {
  return Promise.race([
    waitUntilElementFound(page, '#matafLogoutLink', true, 40000),
    waitUntilElementFound(page, '#validationMsg', true, 40000),
  ]);
}
```
If it will work we can merge it. 

BTW it will not happen to you always, usually it indicate on either slow network on your side or slow server response.

**Comment by razaz** [comment]
thanks for the suggestion, tried and it still fails on timeout.
the behavior is consistent, either running locally or through the action, so my conclusion is that this isnt a network issue.
my next option is to try to debug the url, but if there is any other suggestion on how to debug the behavior with/without the 1s sleep that would help a lot.

**Comment by esakal** [comment]
Hi @razaz ok, we don't have an active list of contributors for each scraper that we can use to get second verification about your issue. But your suggestion shouldn't do any harm.

Feel free to provide a PR and i'll merge it

**Comment by LiranBri** [comment]
I can confirm that I'm also experiencing the same issue. I'll try to take a look but It would take a while as i'm a bit busy currently

**Comment by esakal** [comment]
@LiranBri can you check #697

**Comment by LiranBri** [comment]
@esakal after the package upgrade it doesnt happen anymore.
however, for visa-cal this does happen: https://github.com/eshaham/israeli-bank-scrapers/issues/696

**Comment by esakal** [comment]
@LiranBri great. As we handled #696 I believe we can close this one as well. If needed please create a new issue

**Comment by razaz** [comment]
Resolved with 1s sleep before attempting to login

**Comment by agammyshhay** [comment]
Hi,
i'm using the latest release, and this error still exist - is it happening to other users as well?
